import { Octokit } from "@octokit/rest";

export async function deployToGitHub(
  token: string,
  username: string,
  repoName: string,
  htmlContent: string,
  photoBase64: string,
  photoMimeType: string
): Promise<string> {
  const octokit = new Octokit({ auth: token });

  // Create or get repo
  try {
    await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: "Portfolio website generated by PortfolioBuilder",
      homepage: `https://${username}.github.io/${repoName}`,
      auto_init: false,
      private: false,
    });
  } catch (err: unknown) {
    const error = err as { status?: number };
    if (error.status !== 422) throw err; // 422 = already exists, that's fine
  }

  // Get default branch SHA
  let sha: string | undefined;
  try {
    const { data } = await octokit.repos.getContent({
      owner: username,
      repo: repoName,
      path: "index.html",
    });
    if (!Array.isArray(data)) sha = data.sha;
  } catch {
    // File doesn't exist yet
  }

  // Push index.html
  await octokit.repos.createOrUpdateFileContents({
    owner: username,
    repo: repoName,
    path: "index.html",
    message: "Deploy portfolio website",
    content: Buffer.from(htmlContent).toString("base64"),
    ...(sha ? { sha } : {}),
  });

  // Push profile photo
  let photoSha: string | undefined;
  const photoExt = photoMimeType.includes("png") ? "png" : "jpg";
  const photoPath = `profile.${photoExt}`;

  try {
    const { data } = await octokit.repos.getContent({
      owner: username,
      repo: repoName,
      path: photoPath,
    });
    if (!Array.isArray(data)) photoSha = data.sha;
  } catch {
    // File doesn't exist yet
  }

  await octokit.repos.createOrUpdateFileContents({
    owner: username,
    repo: repoName,
    path: photoPath,
    message: "Add profile photo",
    content: photoBase64,
    ...(photoSha ? { sha: photoSha } : {}),
  });

  // Enable GitHub Pages
  try {
    await octokit.request("POST /repos/{owner}/{repo}/pages", {
      owner: username,
      repo: repoName,
      source: { branch: "main", path: "/" },
    });
  } catch {
    // Pages might already be enabled
  }

  return `https://${username}.github.io/${repoName}`;
}

export async function getGitHubUsername(token: string): Promise<string> {
  const octokit = new Octokit({ auth: token });
  const { data } = await octokit.users.getAuthenticated();
  return data.login;
}
